# Generated by Django 5.1.2 on 2024-11-12 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='toliq-ism')),
                ('username', models.CharField(max_length=75, verbose_name='foydalanuvchi-nomi')),
                ('email', models.CharField(max_length=75, verbose_name='email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Author-image/')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authorlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='nomi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Category-image/')),
            ],
            options={
                'verbose_name': 'kategorya',
                'verbose_name_plural': 'kategoryalar',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='sarlavha')),
                ('content', models.TextField(verbose_name='tarkib')),
                ('date_posted', models.DateField(auto_now=True, verbose_name='nashr-sana')),
                ('author', models.CharField(max_length=75, verbose_name='muallif')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Article-image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.category', verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75, verbose_name='foydalanuvchi-nomi')),
                ('email', models.CharField(max_length=75, verbose_name='email')),
                ('content', models.TextField(verbose_name='matn')),
                ('date_posted', models.DateTimeField(auto_now=True, verbose_name='nashr-sanasi')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.article', verbose_name='maqola')),
            ],
            options={
                'verbose_name': 'sharx',
                'verbose_name_plural': 'sharxlar',
            },
        ),
    ]
